version: '2'
services:
  jm-app:
    image: testtask
    environment:
      - 'spring.datasource.url=jdbc:postgresql://jm-postgres:5432/testtask'
    ports:
      - "8081:8081"
    depends_on:
      - jm-postgres
  jm-postgres:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testtask

